### ISSUE TITLE
  Error executing callback ui_tabs_callback for M:\SD\git\sdxlwebui\extensions\sd-webui-chatgpt\scripts\main.py  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by swumagic** [NON906/sd-webui-chatgpt#1]
*** Error executing callback ui_tabs_callback for M:\SD\git\sdxlwebui\extensions\sd-webui-chatgpt\scripts\main.py
    Traceback (most recent call last):
      File "M:\SD\git\sdxlwebui\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-chatgpt\scripts\main.py", line 41, in on_ui_tabs
        init_txt2img_params()
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-chatgpt\scripts\main.py", line 36, in init_txt2img_params
        txt2img_params_base = json.loads(txt2img_params_json)
      File "M:\SD\Python31011\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "M:\SD\Python31011\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "M:\SD\Python31011\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

To create a public link, set `share=True` in `launch()`.
*** Error executing callback app_started_callback for M:\SD\git\sdxlwebui\extensions\sd-webui-chatgpt\scripts\main.py
    Traceback (most recent call last):
      File "M:\SD\git\sdxlwebui\modules\script_callbacks.py", line 126, in app_started_callback
        c.callback(demo, app)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-chatgpt\scripts\main.py", line 323, in on_started
        lines = public_ui_value['json_settings'].count('\n') + 1
    KeyError: 'json_settings'

**Comment by NON906** [comment]
I didn't get the same error here.
But, I changed the part that seems to be the cause.
So, please check new commit (89ad33e5158baad12916e0d5d59a73e9051c7a05).
